# Generated by Django 4.1.3 on 2023-01-19 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFollowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='User.profile')),
                ('following_users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='User.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='Me',
        ),
    ]
