# Generated by Django 4.1.3 on 2023-01-19 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_userfollowing_delete_me'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfollowing',
            old_name='followed_users',
            new_name='followed',
        ),
        migrations.RenameField(
            model_name='userfollowing',
            old_name='following_users',
            new_name='following',
        ),
    ]
