# Generated by Django 4.1.3 on 2023-01-19 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_rename_followed_users_userfollowing_followed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfollowing',
            old_name='following',
            new_name='following_user',
        ),
        migrations.RenameField(
            model_name='userfollowing',
            old_name='followed',
            new_name='user',
        ),
    ]
