# Generated by Django 3.2.17 on 2023-02-09 16:28

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('User', '0008_remove_likecomment_comment_remove_likecomment_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='profile',
            name='fav_anime',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
    ]
